In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
df = pd.read_csv("face_feature_vectors.csv")
df

Unnamed: 0 Unnamed: 1         0         1         2         3         4  \
0             1       male -0.066420  0.151611  0.027740  0.052771 -0.066105   
1             2       male -0.030614  0.049667  0.008084 -0.050324  0.007649   
2             3       male -0.096178  0.061127  0.035326 -0.035388 -0.090728   
3             4       male -0.103057  0.085044  0.078333 -0.035873 -0.028163   
4             5       male -0.125815  0.120046  0.023131 -0.042901  0.038215   
..          ...        ...       ...       ...       ...       ...       ...   
795         796     female -0.164731  0.064301  0.058630 -0.017420 -0.157600   
796         797     female -0.095308  0.051095  0.092913 -0.101745 -0.083153   
797         798     female -0.202852  0.037039  0.079731 -0.047156 -0.140062   
798         799     female -0.088300  0.063530  0.049627 -0.026011 -0.172773   
799         800     female -0.156201  0.055165  0.142716 -0.115393 -0.128982   

            5         6         7  ...       118       119       120  \
0   -0.041232 -0.002637 -0.158467  ...  0.025989 -0.001087  0.027260   
1   -0.063818 -0.019530 -0.119905  ...  0.044229 -0.023900 -0.028108   
2   -0.018634 -0.024315 -0.139786  ...  0.111141  0.059436 -0.029222   
3    0.004924  0.007829 -0.017016  ...  0.100793 -0.002644 -0.023388   
4   -0.049677 -0.054258 -0.130758  ...  0.090197  0.067527  0.039926   
..        ...       ...       ...  ...       ...       ...       ...   
795 -0.022536  0.002864 -0.072739  ...  0.095115  0.007198 -0.004655   
796 -0.028159  0.009090 -0.114513  ...  0.056078  0.119846  0.087470   
797 -0.080246  0.057668 -0.122083  ...  0.066954  0.035684 -0.023112   
798  0.086218  0.042710 -0.161852  ...  0.039460  0.067547  0.040426   
799 -0.139830 -0.037305 -0.101402  ...  0.024955  0.066980 -0.002332   

          121       122       123       124       125       126       127  
0   -0.046754 -0.118619 -0.163774 -0.000590 -0.076400  0.107497  0.001567  
1    0.040618 -0.146579 -0.141244  0.016162  0.017638  0.080610 -0.015930  
2    0.042115 -0.222173 -0.116908  0.093428  0.017391  0.057652  0.086116  
3    0.029497 -0.139830 -0.119243  0.005306 -0.015100  0.161575  0.062462  
4    0.047469 -0.056852 -0.076700  0.004966  0.028171  0.026041  0.084135  
..        ...       ...       ...       ...       ...       ...       ...  
795  0.023957 -0.170753 -0.136630  0.041614  0.031600  0.019064  0.004384  
796  0.017481 -0.096594 -0.084553  0.037709  0.030732 -0.083713  0.064970  
797 -0.030452 -0.154243 -0.188270  0.071086  0.037384 -0.006257  0.039977  
798  0.028007 -0.154515 -0.127736  0.046967  0.009701 -0.016942  0.048071  
799 -0.045738 -0.110557 -0.014995 -0.002124 -0.010298 -0.028856  0.075323  

[800 rows x 130 columns]

In [3]:
male = df.iloc[0:395,2:] #getting the male training data
male

0         1         2         3         4         5         6  \
0   -0.066420  0.151611  0.027740  0.052771 -0.066105 -0.041232 -0.002637   
1   -0.030614  0.049667  0.008084 -0.050324  0.007649 -0.063818 -0.019530   
2   -0.096178  0.061127  0.035326 -0.035388 -0.090728 -0.018634 -0.024315   
3   -0.103057  0.085044  0.078333 -0.035873 -0.028163  0.004924  0.007829   
4   -0.125815  0.120046  0.023131 -0.042901  0.038215 -0.049677 -0.054258   
..        ...       ...       ...       ...       ...       ...       ...   
390 -0.080683  0.097440  0.006550  0.018112 -0.114999  0.160041 -0.002373   
391 -0.010301  0.135185  0.049710 -0.046424 -0.041742  0.016607 -0.041778   
392 -0.112450  0.080098  0.030571  0.000952 -0.097450 -0.045070 -0.003641   
393 -0.087855  0.100264  0.069775  0.037204 -0.047182 -0.047233 -0.013604   
394 -0.139066  0.141988  0.070456 -0.003518 -0.065637 -0.037767 -0.094195   

            7         8         9  ...       118       119       120  \
0   -0.158467  0.130467 -0.044872  ...  0.025989 -0.001087  0.027260   
1   -0.119905  0.186553 -0.044821  ...  0.044229 -0.023900 -0.028108   
2   -0.139786  0.052211 -0.052085  ...  0.111141  0.059436 -0.029222   
3   -0.017016  0.114907 -0.056267  ...  0.100793 -0.002644 -0.023388   
4   -0.130758  0.173457 -0.011889  ...  0.090197  0.067527  0.039926   
..        ...       ...       ...  ...       ...       ...       ...   
390 -0.057956  0.076157 -0.006223  ...  0.089160  0.073848  0.030187   
391 -0.048020  0.234796 -0.065025  ...  0.090084  0.091338  0.022718   
392 -0.142828  0.145999 -0.017251  ...  0.054003  0.013400  0.050133   
393 -0.189378  0.125076 -0.037503  ...  0.108849  0.140784 -0.039212   
394 -0.195665  0.070896 -0.044215  ...  0.125822  0.039625  0.067861   

          121       122       123       124       125       126       127  
0   -0.046754 -0.118619 -0.163774 -0.000590 -0.076400  0.107497  0.001567  
1    0.040618 -0.146579 -0.141244  0.016162  0.017638  0.080610 -0.015930  
2    0.042115 -0.222173 -0.116908  0.093428  0.017391  0.057652  0.086116  
3    0.029497 -0.139830 -0.119243  0.005306 -0.015100  0.161575  0.062462  
4    0.047469 -0.056852 -0.076700  0.004966  0.028171  0.026041  0.084135  
..        ...       ...       ...       ...       ...       ...       ...  
390 -0.071334 -0.175275 -0.100638  0.055430 -0.045177 -0.017163  0.027779  
391  0.057871 -0.064987 -0.127295 -0.063550  0.010827  0.007755  0.011586  
392 -0.039018 -0.134093 -0.034270  0.083867  0.007422  0.001248  0.076941  
393  0.041003 -0.127442 -0.022349  0.104111  0.024425  0.039480 -0.030288  
394  0.134050 -0.178726 -0.100577  0.015707 -0.005463  0.001857  0.079183  

[395 rows x 128 columns]

In [4]:
female = df.iloc[400:795,2:]  #getting the female training data
female

0         1         2         3         4         5         6  \
400  0.001747  0.185678  0.073260  0.042142 -0.088674  0.028186 -0.027830   
401 -0.091598  0.095340  0.072125 -0.092276 -0.079953  0.047782 -0.004701   
402 -0.018751  0.088572  0.068894 -0.065700 -0.115126  0.024339 -0.028420   
403 -0.130889  0.093262  0.122244 -0.110014 -0.157625 -0.036781  0.073908   
404 -0.037433  0.078158  0.118061 -0.117658 -0.194807 -0.045464 -0.014104   
..        ...       ...       ...       ...       ...       ...       ...   
790 -0.184166  0.122040  0.064143 -0.116653 -0.140633  0.041252  0.014207   
791 -0.128052  0.082184  0.148978 -0.074984 -0.113145 -0.031003  0.018468   
792 -0.109618  0.094507  0.043757 -0.162004 -0.191951  0.027582 -0.033507   
793 -0.201133  0.068051  0.088596 -0.084936 -0.055628 -0.069027 -0.003922   
794 -0.185053  0.136105  0.096279 -0.139661 -0.244312  0.015234 -0.007418   

            7         8         9  ...       118       119       120  \
400 -0.064211  0.097413 -0.010493  ...  0.123615  0.030036  0.041442   
401 -0.092005  0.222913 -0.059830  ...  0.011370  0.144719  0.089139   
402 -0.159320  0.164595 -0.116339  ...  0.010345  0.095309  0.012255   
403 -0.098571  0.120419 -0.016198  ...  0.003229  0.049330  0.059733   
404 -0.158824  0.159272 -0.112154  ...  0.043848 -0.009760  0.043486   
..        ...       ...       ...  ...       ...       ...       ...   
790 -0.108811  0.222441 -0.092586  ...  0.056709  0.022346  0.086402   
791 -0.130281  0.151299 -0.070118  ...  0.097865  0.159616  0.043723   
792 -0.112072  0.223496 -0.149295  ...  0.065094  0.086847  0.048039   
793 -0.191394  0.156983 -0.110330  ...  0.002213  0.069219 -0.086575   
794 -0.077617  0.154104 -0.014435  ...  0.124050  0.088145  0.114959   

          121       122       123       124       125       126       127  
400 -0.012818 -0.119177 -0.165786 -0.075368 -0.017690  0.067028  0.036452  
401 -0.059767 -0.111235 -0.055420  0.006283  0.016900 -0.081676  0.022809  
402 -0.033010 -0.097720 -0.218889  0.077764  0.045943  0.010856  0.100522  
403 -0.023820 -0.098432 -0.034316  0.075131 -0.029204 -0.020707  0.031028  
404  0.020251 -0.115420 -0.040023  0.099409 -0.032240  0.037601 -0.020016  
..        ...       ...       ...       ...       ...       ...       ...  
790  0.034427 -0.192231 -0.124329  0.099240 -0.056921 -0.050119  0.077761  
791 -0.050682 -0.047764 -0.096516 -0.040761 -0.009942 -0.013904  0.091586  
792 -0.029331 -0.096296 -0.093692  0.042464 -0.054497  0.009432  0.135039  
793 -0.015379 -0.114221 -0.043949  0.116332 -0.068063 -0.000160  0.021194  
794  0.059632 -0.014315 -0.131909  0.013280 -0.090556 -0.026245  0.102910  

[395 rows x 128 columns]

## COMPUTING THE COVARIANCE MATRICES

In [5]:
male_cov = male.cov()  #computing the covariance matrix
male_cov

0         1         2         3         4         5         6  \
0    0.003110 -0.000565 -0.000329  0.000217  0.000225  0.000176 -0.000616   
1   -0.000565  0.002271  0.000373 -0.000160 -0.000084  0.000723 -0.000706   
2   -0.000329  0.000373  0.002510  0.000520  0.000282 -0.000442 -0.000323   
3    0.000217 -0.000160  0.000520  0.001955  0.000406 -0.000422  0.000139   
4    0.000225 -0.000084  0.000282  0.000406  0.002757 -0.001035  0.000331   
..        ...       ...       ...       ...       ...       ...       ...   
123 -0.000832  0.000091  0.000576  0.000142  0.000822 -0.000330  0.000506   
124 -0.001123  0.000423 -0.000072 -0.000434 -0.000236  0.000247  0.000305   
125  0.000622 -0.000359 -0.000364 -0.000172  0.000939 -0.000815 -0.000012   
126 -0.000198 -0.000292  0.000097 -0.000095 -0.000030 -0.000784  0.000216   
127 -0.000104 -0.000205 -0.000075 -0.000176 -0.000558 -0.000040  0.000064   

            7         8         9  ...       118       119       120  \
0    0.000139 -0.000300 -0.000329  ... -0.000084  0.000525 -0.000114   
1    0.000137  0.000353  0.000315  ...  0.000445  0.000198  0.000298   
2    0.000278 -0.000209 -0.000483  ... -0.000005 -0.000035 -0.000456   
3   -0.000578 -0.000396 -0.000199  ... -0.000562  0.000499 -0.000443   
4   -0.000414  0.000373  0.000009  ... -0.000392  0.000339 -0.000324   
..        ...       ...       ...  ...       ...       ...       ...   
123 -0.000042  0.000467  0.000415  ... -0.000223  0.000070 -0.000158   
124  0.000034  0.000036  0.000158  ...  0.000126 -0.000473  0.000352   
125 -0.000179 -0.000136 -0.000019  ...  0.000063 -0.000104 -0.000277   
126 -0.000372 -0.000027 -0.000185  ...  0.000473 -0.000467 -0.000287   
127 -0.000230 -0.000342 -0.000097  ...  0.000190  0.000316  0.000026   

          121       122       123       124       125       126       127  
0    0.000170 -0.000417 -0.000832 -0.001123  0.000622 -0.000198 -0.000104  
1   -0.000214  0.000368  0.000091  0.000423 -0.000359 -0.000292 -0.000205  
2   -0.000010  0.000211  0.000576 -0.000072 -0.000364  0.000097 -0.000075  
3    0.000134 -0.000155  0.000142 -0.000434 -0.000172 -0.000095 -0.000176  
4    0.000375 -0.000040  0.000822 -0.000236  0.000939 -0.000030 -0.000558  
..        ...       ...       ...       ...       ...       ...       ...  
123 -0.000300  0.000045  0.002413  0.000713  0.000085 -0.000042 -0.000396  
124 -0.000796  0.000138  0.000713  0.002769  0.000181  0.000322 -0.000342  
125 -0.000205 -0.000163  0.000085  0.000181  0.002428  0.000060 -0.000002  
126  0.000199  0.000381 -0.000042  0.000322  0.000060  0.002471  0.000265  
127  0.000577 -0.000466 -0.000396 -0.000342 -0.000002  0.000265  0.001762  

[128 rows x 128 columns]

In [6]:
female_cov = female.cov()  #computing the covariance matrix
female_cov

0         1         2             3         4         5  \
0    2.484266e-03 -0.000369  0.000371 -7.692441e-07  0.000325  0.000066   
1   -3.691821e-04  0.002590  0.000047 -1.587192e-05 -0.000289  0.000837   
2    3.712169e-04  0.000047  0.001934 -3.733706e-05 -0.000127  0.000122   
3   -7.692441e-07 -0.000016 -0.000037  1.582478e-03 -0.000088  0.000024   
4    3.248240e-04 -0.000289 -0.000127 -8.819215e-05  0.002392 -0.000331   
..            ...       ...       ...           ...       ...       ...   
123  3.295382e-05 -0.000130 -0.000107 -2.584048e-04  0.000345 -0.000488   
124 -2.012233e-04 -0.000338 -0.000383  6.275051e-05  0.000289 -0.000388   
125  1.810819e-04 -0.000456 -0.000138 -1.249101e-04  0.000543 -0.000310   
126 -2.007050e-04 -0.000130 -0.000186  6.003919e-05  0.000113 -0.000539   
127 -1.547928e-04  0.000069  0.000390 -3.420847e-04 -0.000631  0.000187   

            6         7         8         9  ...       118       119  \
0   -0.000211  0.000167 -0.000073 -0.000176  ... -0.000245  0.000091   
1   -0.000610 -0.000193  0.000110  0.000443  ...  0.000772  0.000227   
2   -0.000180  0.000263 -0.000432  0.000125  ...  0.000205  0.000114   
3    0.000232 -0.000067 -0.000316  0.000027  ... -0.000198 -0.000016   
4    0.000159 -0.000441  0.000259 -0.000120  ... -0.000252  0.000387   
..        ...       ...       ...       ...  ...       ...       ...   
123 -0.000084 -0.000262  0.000206  0.000377  ...  0.000098  0.000395   
124  0.000679 -0.000265 -0.000382 -0.000184  ... -0.000119 -0.000243   
125  0.000456  0.000155  0.000074 -0.000106  ... -0.000479 -0.000107   
126  0.000129 -0.000180 -0.000061 -0.000244  ...  0.000636 -0.000326   
127 -0.000377  0.000021 -0.000351  0.000181  ...  0.000229  0.000449   

          120       121       122       123       124       125       126  \
0   -0.000006 -0.000184 -0.000433  0.000033 -0.000201  0.000181 -0.000201   
1    0.000565 -0.000148  0.000385 -0.000130 -0.000338 -0.000456 -0.000130   
2   -0.000076  0.000330  0.000211 -0.000107 -0.000383 -0.000138 -0.000186   
3   -0.000309 -0.000218  0.000171 -0.000258  0.000063 -0.000125  0.000060   
4   -0.000326  0.000235 -0.000396  0.000345  0.000289  0.000543  0.000113   
..        ...       ...       ...       ...       ...       ...       ...   
123 -0.000196 -0.000171 -0.000013  0.002287  0.000206 -0.000078  0.000127   
124 -0.000518  0.000190 -0.000347  0.000206  0.002241  0.000480  0.000800   
125 -0.000364  0.000077 -0.000139 -0.000078  0.000480  0.002266 -0.000100   
126 -0.000508  0.000172  0.000034  0.000127  0.000800 -0.000100  0.002347   
127  0.000655  0.000621  0.000055 -0.000521 -0.000539  0.000286 -0.000290   

          127  
0   -0.000155  
1    0.000069  
2    0.000390  
3   -0.000342  
4   -0.000631  
..        ...  
123 -0.000521  
124 -0.000539  
125  0.000286  
126 -0.000290  
127  0.002698  

[128 rows x 128 columns]

In [7]:
inv_cov_male = np.linalg.inv(male_cov)
inv_cov_male

array([[ 6.41719862e+13,  2.59041200e+12,  1.63587452e+13, ...,
         3.04289907e+12, -1.48333016e+13,  3.51444208e+13],
       [ 2.59196492e+12,  1.00154724e+14, -9.78217086e+12, ...,
         6.41329687e+12,  1.70047116e+13,  3.07518037e+12],
       [ 1.63598967e+13, -9.77974001e+12,  6.37720246e+13, ...,
        -1.03132669e+13, -1.36554102e+13, -1.88358143e+13],
       ...,
       [ 3.04587874e+12,  6.40899962e+12, -1.03162207e+13, ...,
         8.10018777e+13,  1.24173956e+13, -7.13067535e+12],
       [-1.48271108e+13,  1.70021556e+13, -1.36510063e+13, ...,
         1.24208845e+13,  1.20501322e+14, -3.19056208e+12],
       [ 3.51400411e+13,  3.07652103e+12, -1.88391286e+13, ...,
        -7.13599165e+12, -3.18883962e+12,  1.20837434e+14]],
      shape=(128, 128))

In [8]:
inv_cov_female = np.linalg.inv(female_cov)
inv_cov_female

array([[ 7.56416999e+13, -4.84992693e+12,  2.03654815e+13, ...,
         1.03562913e+12, -2.87876857e+13,  3.88626317e+13],
       [-4.85181693e+12,  7.80254155e+13, -1.84348555e+13, ...,
         7.61051778e+12,  1.29056417e+13, -1.14534114e+11],
       [ 2.03639837e+13, -1.84357555e+13,  7.00431767e+13, ...,
        -1.02181114e+13, -2.44483474e+13, -8.21332687e+12],
       ...,
       [ 1.03076309e+12,  7.61194323e+12, -1.02195178e+13, ...,
         7.54806288e+13,  2.32846309e+13, -9.62178033e+12],
       [-2.87893543e+13,  1.29022788e+13, -2.44489887e+13, ...,
         2.32835320e+13,  1.23504831e+14,  1.05704167e+13],
       [ 3.88638107e+13, -1.14805297e+11, -8.21043365e+12, ...,
        -9.62050787e+12,  1.05673167e+13,  1.37028711e+14]],
      shape=(128, 128))

## CASE 3 OF BAYES CLASSIFIER

In [9]:
W1 = -0.5*inv_cov_male
W1

array([[-3.20859931e+13, -1.29520600e+12, -8.17937258e+12, ...,
        -1.52144953e+12,  7.41665081e+12, -1.75722104e+13],
       [-1.29598246e+12, -5.00773622e+13,  4.89108543e+12, ...,
        -3.20664844e+12, -8.50235579e+12, -1.53759019e+12],
       [-8.17994834e+12,  4.88987001e+12, -3.18860123e+13, ...,
         5.15663347e+12,  6.82770508e+12,  9.41790717e+12],
       ...,
       [-1.52293937e+12, -3.20449981e+12,  5.15811036e+12, ...,
        -4.05009389e+13, -6.20869778e+12,  3.56533768e+12],
       [ 7.41355540e+12, -8.50107778e+12,  6.82550313e+12, ...,
        -6.21044227e+12, -6.02506611e+13,  1.59528104e+12],
       [-1.75700205e+13, -1.53826052e+12,  9.41956431e+12, ...,
         3.56799582e+12,  1.59441981e+12, -6.04187169e+13]],
      shape=(128, 128))

In [10]:
W2 = -0.5*inv_cov_female
W2

array([[-3.78208500e+13,  2.42496347e+12, -1.01827408e+13, ...,
        -5.17814566e+11,  1.43938428e+13, -1.94313159e+13],
       [ 2.42590847e+12, -3.90127077e+13,  9.21742776e+12, ...,
        -3.80525889e+12, -6.45282085e+12,  5.72670570e+10],
       [-1.01819919e+13,  9.21787777e+12, -3.50215883e+13, ...,
         5.10905571e+12,  1.22241737e+13,  4.10666344e+12],
       ...,
       [-5.15381545e+11, -3.80597162e+12,  5.10975892e+12, ...,
        -3.77403144e+13, -1.16423154e+13,  4.81089016e+12],
       [ 1.43946772e+13, -6.45113942e+12,  1.22244944e+13, ...,
        -1.16417660e+13, -6.17524155e+13, -5.28520833e+12],
       [-1.94319053e+13,  5.74026483e+10,  4.10521682e+12, ...,
         4.81025393e+12, -5.28365835e+12, -6.85143557e+13]],
      shape=(128, 128))

In [11]:
mean1 = male.mean()
mean1

0     -0.091073
1      0.092546
2      0.043410
3     -0.030380
4     -0.092752
         ...   
123   -0.118276
124    0.021995
125   -0.024923
126    0.020072
127    0.039999
Length: 128, dtype: float64

In [12]:
mean2 = female.mean()
mean2

0     -0.116613
1      0.077229
2      0.082055
3     -0.077577
4     -0.122836
         ...   
123   -0.087036
124    0.053702
125   -0.032008
126    0.003974
127    0.026298
Length: 128, dtype: float64

In [13]:
w1 = np.matmul(inv_cov_male,mean1)
w1

array([-9.35582963e+07,  7.00174900e+07,  1.91029392e+08,  2.09656103e+08,
       -2.56583991e+08,  2.51600592e+08,  7.31294296e+07,  5.89267174e+07,
       -9.28206732e+07,  3.25288591e+07, -1.66302729e+08, -1.93384280e+08,
        6.96313486e+07, -6.53216642e+07,  7.84795606e+07,  4.94677706e+06,
       -5.34577693e+07,  1.76115903e+08, -4.49076253e+07, -6.53669103e+07,
        1.29033512e+08, -2.26287262e+08, -1.70094877e+07, -1.63669240e+08,
        4.01607969e+08,  1.72494863e+08, -4.00187057e+08, -3.85543479e+08,
        1.53582619e+08,  4.25715301e+07,  1.39589952e+08,  6.77269591e+07,
       -7.40187922e+07, -6.54543222e+07,  2.03339705e+08,  1.93713764e+08,
       -9.14333563e+07, -3.12232985e+07, -1.35193737e+08,  2.14315494e+08,
       -1.34701543e+08, -7.79652231e+07, -2.63782647e+08,  3.45255755e+07,
        1.21643393e+07, -1.30853660e+08,  6.22962347e+07, -9.91049271e+07,
        1.65964296e+08, -1.59659261e+08,  9.45056082e+07,  1.39882442e+08,
       -1.03026218e+07,  

In [14]:
w2 = np.matmul(inv_cov_female,mean2)
w2

array([-5.88056513e+07, -1.56420571e+07,  5.70983308e+07,  5.07874556e+07,
       -1.87943945e+08,  2.45596155e+07,  1.08383987e+08, -3.70853257e+07,
       -2.62423503e+08, -6.44902679e+07, -2.62855115e+08,  6.90928938e+07,
        7.52461225e+07, -1.16110454e+08,  4.56098781e+07, -2.84657024e+07,
       -6.46200274e+07,  7.52343165e+07,  1.22992154e+08, -1.70744438e+08,
       -3.58482341e+07, -7.79856791e+06, -7.89924826e+07, -1.03199939e+08,
        1.23327175e+08, -1.62747336e+07, -6.26642022e+07, -1.52488836e+08,
        1.75325635e+08, -4.06269322e+07,  1.78558776e+08, -1.10268065e+08,
        1.92951583e+07, -3.49303873e+08,  1.08719738e+07,  2.01917654e+08,
       -2.42656661e+06, -7.79292079e+07, -5.95860353e+07,  3.14743600e+08,
       -3.72960076e+07, -1.92452204e+08, -2.53327296e+08, -5.64365885e+07,
       -7.73710532e+07,  2.75475386e+07,  1.14327613e+08, -2.03986409e+07,
        1.37924630e+07, -8.63380730e+07,  3.94356669e+07,  8.70854756e+07,
       -1.36652257e+07,  

In [15]:
constant_1 = -0.5*(np.matmul(np.matmul(mean1.transpose(),inv_cov_male),mean1))
constant_1

np.float64(-4986.775328114629)

In [16]:
constant_2 = -0.5*(np.matmul(np.matmul(mean2.transpose(),inv_cov_female),mean2))
constant_2

np.float64(-5495.921426787972)

## TESTING DATA AND BAYES CLASSIFICATION

In [17]:
testing_data = df.iloc[395:400,2:]  #male testing data
testing_data

0         1         2         3         4         5         6  \
395 -0.129449  0.132177  0.055916 -0.009390 -0.080541 -0.072362 -0.067433   
396 -0.158460  0.109948  0.019088  0.015506 -0.069668  0.032311  0.015062   
397 -0.101499  0.119739  0.016951 -0.013677 -0.055524  0.028399  0.028164   
398 -0.149516  0.081588  0.090796 -0.053116 -0.133314  0.001096  0.019941   
399  0.039844  0.070357  0.130196 -0.007683 -0.077825 -0.021298 -0.024133   

            7         8         9  ...       118       119       120  \
395 -0.192243  0.108654 -0.052347  ...  0.142675  0.028204 -0.010465   
396 -0.140817  0.141132 -0.036736  ...  0.143453  0.059608 -0.006824   
397 -0.152100  0.109814 -0.012079  ...  0.046488  0.051044 -0.008298   
398 -0.117803  0.102320 -0.097426  ...  0.111678 -0.016921  0.059115   
399 -0.085105  0.071288 -0.121256  ...  0.105510  0.081928 -0.033337   

          121       122       123       124       125       126       127  
395  0.002703 -0.117138 -0.148947  0.054327  0.004200  0.046730  0.037774  
396  0.056758 -0.064352 -0.108518  0.132037  0.050347  0.071465 -0.022954  
397  0.018010 -0.164197 -0.122292  0.032616 -0.030194 -0.018642  0.032821  
398 -0.007810 -0.096824 -0.079415 -0.015487 -0.075470  0.062481  0.052727  
399 -0.023604 -0.167003 -0.059075  0.053074  0.080940  0.011467 -0.021999  

[5 rows x 128 columns]

In [18]:
#we substitute the feature vector X in the case 3 of the Bayes decision theory and we get 100% accuracy
for i in testing_data.index:
    curr_row = testing_data.loc[i]
    g1 = np.matmul(np.matmul(curr_row.transpose(),W1),curr_row) + np.matmul(w1.transpose(),curr_row) + constant_1
    g2 = np.matmul(np.matmul(curr_row.transpose(),W2),curr_row) + np.matmul(w2.transpose(),curr_row) + constant_2
    if g1 > g2:
        print("male")
    else:
        print("female")

male
male
male
male
male


In [19]:
testing_data = df.iloc[795:800,2:]  #female testing data
testing_data

0         1         2         3         4         5         6  \
795 -0.164731  0.064301  0.058630 -0.017420 -0.157600 -0.022536  0.002864   
796 -0.095308  0.051095  0.092913 -0.101745 -0.083153 -0.028159  0.009090   
797 -0.202852  0.037039  0.079731 -0.047156 -0.140062 -0.080246  0.057668   
798 -0.088300  0.063530  0.049627 -0.026011 -0.172773  0.086218  0.042710   
799 -0.156201  0.055165  0.142716 -0.115393 -0.128982 -0.139830 -0.037305   

            7         8         9  ...       118       119       120  \
795 -0.072739  0.030554 -0.121480  ...  0.095115  0.007198 -0.004655   
796 -0.114513  0.157421 -0.069665  ...  0.056078  0.119846  0.087470   
797 -0.122083  0.165443 -0.104478  ...  0.066954  0.035684 -0.023112   
798 -0.161852  0.185083 -0.162894  ...  0.039460  0.067547  0.040426   
799 -0.101402  0.048473 -0.041618  ...  0.024955  0.066980 -0.002332   

          121       122       123       124       125       126       127  
795  0.023957 -0.170753 -0.136630  0.041614  0.031600  0.019064  0.004384  
796  0.017481 -0.096594 -0.084553  0.037709  0.030732 -0.083713  0.064970  
797 -0.030452 -0.154243 -0.188270  0.071086  0.037384 -0.006257  0.039977  
798  0.028007 -0.154515 -0.127736  0.046967  0.009701 -0.016942  0.048071  
799 -0.045738 -0.110557 -0.014995 -0.002124 -0.010298 -0.028856  0.075323  

[5 rows x 128 columns]

In [20]:
#we substitute the feature vector X in the case 3 of the Bayes decision theory and we get 100% accuracy
for i in testing_data.index:
    curr_row = testing_data.loc[i]
    g1 = np.matmul(np.matmul(curr_row.transpose(),W1),curr_row) + np.matmul(w1.transpose(),curr_row) + constant_1
    g2 = np.matmul(np.matmul(curr_row.transpose(),W2),curr_row) + np.matmul(w2.transpose(),curr_row) + constant_2
    if g1 > g2:
        print("male")
    else:
        print("female")

female
female
female
female
female
